### ISSUE TITLE
TimeToLiveSpecification Invalid Parameter Error

### ISSUE THREAD

**Issue by benswinburne** [sdd/serverless-dynalite#5]
Having added `TimeToLiveSpecification` to my DynamoDB configuration as CloudFormation supports it, Dynalite seems to kick up a fuss about invalid parameters.

See https://github.com/Jimdo/serverless-dynamodb-ttl/issues/16#issuecomment-365354707

Whilst I gather it may not support TTL, I assume it shouldn't fall over at valid CloudFormation parameters?

Cheers

```
Serverless: Listening for table additions / deletions.
(node:18227) UnhandledPromiseRejectionWarning: UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params
    at ParamValidator.fail (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/x/Sites/y/project/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/config.js:320:7)
    at /Users/x/Sites/y/project/node_modules/aws-sdk/lib/config.js:338:9
    at SharedIniFileCredentials.get (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/config.js:332:24)
    at Config.getCredentials (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/config.js:352:9)
    at Request.VALIDATE_CREDENTIALS (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/request.js:403:15)
    at /Users/x/Sites/y/project/node_modules/aws-sdk/lib/request.js:791:12
    at new Promise (<anonymous>)
    at Request.promise (/Users/x/Sites/y/project/node_modules/aws-sdk/lib/request.js:777:12)
    at ServerlessDynalite._callee4$ (/Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:212:103)
    at tryCatch (/Users/x/Sites/y/project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/x/Sites/y/project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/x/Sites/y/project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:5:191)
    at /Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:5:437
    at new Promise (<anonymous>)
    at /Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:5:99
    at /Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:223:54
    at arrayEach (/Users/x/Sites/y/project/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/x/Sites/y/project/node_modules/lodash/lodash.js:9359:14)
    at ServerlessDynalite._callee6$ (/Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:204:35)
    at tryCatch (/Users/x/Sites/y/project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/x/Sites/y/project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/x/Sites/y/project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:5:191)
    at /Users/x/Sites/y/project/node_modules/serverless-dynalite/distribution/index.js:5:361
    at <anonymous>
```

**Comment by faizhasim** [comment]
Similarly for other parameters. I got this: `UnexpectedParameter: Unexpected key 'PointInTimeRecoverySpecification' found in params`.

I reckon a fix can be done similarly to https://github.com/99xt/serverless-dynamodb-local/pull/168/files#diff-168726dbe96b3ce427e7fedce31bb0bcR283.
